(tool-bar-mode -1)
(set-default 'cursor-type 'hbar)
(show-paren-mode)
(global-hl-line-mode)
(require 'package)
(add-to-list 'package-archives
	     '("melpa" . "http://melpa.milkbox.net/packages/")
	     t)
(add-to-list 'package-archives
	     '("marmalade" . "http://marmalade-repo.org/packages/")
	     t)
(package-initialize)
(load-theme 'monokai t)
(global-set-key (kbd "M-x") 'smex)
(global-set-key (kbd "C-c C-c M-x") 'execute-extended-command)
(ac-config-default)
(nlinum-mode)
(autopair-global-mode)
(global-undo-tree-mode)
(global-set-key (kbd "M-/") 'undo-tree-visualize)
(global-set-key (kbd "C-M-z") 'switch-window)
(global-set-key (kbd "C->") 'ace-jump-mode)
